services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: devops1
      MYSQL_DATABASE: taskiteasy2
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000

  phpmyadmin:
    build:
      context: .
      dockerfile: Dockerfile.phpmyadmin
    container_name: my-phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: my-mysql
      MYSQL_ROOT_PASSWORD: devops1
    ports:
      - "8080:80"

volumes:
  mysql-data:
